### ISSUE TITLE
Image uploading fails after SUPEE-8788 patch

### ISSUE THREAD

**Issue by jimmydg** [Adyen/adyen-magento#682] opened 2016-10-14 11:24 UTC
Uploading product images fails after the SUPEE-8788 patch

```
2016-10-14T11:21:13+00:00 ERR (3): Warning: pack(): Type H: illegal hex digit o  in public/app/code/community/Adyen/Payment/Model/Observer.php on line 399
2016-10-14T11:21:13+00:00 ERR (3): Warning: pack(): Type H: illegal hex digit h  in public/app/code/community/Adyen/Payment/Model/Observer.php on line 399
2016-10-14T11:21:13+00:00 ERR (3): Warning: pack(): Type H: illegal hex digit m  in public/app/code/community/Adyen/Payment/Model/Observer.php on line 399
```

**Comment by rikterbeek** [comment] 2016-10-14 12:21
Hi @jimmydg,

Strange, is this error occurring on multiple pages ?

Regards,
Rik

**Comment by rikterbeek** [comment] 2016-10-14 14:29
Hi @jimmydg,

Could not reproduce it myself I know the patch has updated the whole upload mechanisme but that is something outside our module.

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment] 2016-10-21 11:03
IMHO that is related to a HPP HMAC Key not in Hex format. 
I presume that you are working locally on an old DB, where the Adyen module is configured to work with a HMAC-SHA1 HPP key, but the installed module requires a HMAC-SHA256 key.
So you just have to edit the system configuration, in the HPP section delete (or update) the "HMAC Key for Test" and "HMAC Key for Live" fields.

**Comment by rikterbeek** [comment] 2016-10-27 12:30
Hi @jimmydg,

I close the issue for now let me know if you still have problems.

Regards,
Rik
Adyen

**Closed by rikterbeek** 2016-10-27 12:30 UTC
