### ISSUE TITLE
Since 10 april orders /w status new are set back to pending

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#768] opened 2017-04-15 06:33 UTC
'See some issues since 11 april where order is authorized, markes as status new

And then shortly after reset to status pending

Just found 4 cases

![image](https://cloud.githubusercontent.com/assets/652395/25422878/c6d337e0-2a62-11e7-9385-e6c4039f2695.png)

Was something changed in process? version 2.8.1

**Comment by shanelja** [comment] 2017-04-15 07:58
Hi @seansan, this seems most likely to be a bug in the rest of your codebase or your configuration. Since you haven't yet upgraded to 2.9.0, your codebase has been stable since December of 2016 and this issue hasn't yet been reported which seems unlikely based solely on the large userbase.

Having read the 2.9.0 release notes and performed a full audit on the code included in the release, I don't believe that upgrading will fix this issue for you.

In my mind, the most likely issue will be an incorrect update to your Adyen module configuration or an update to how your websites order statuses work which no longer aligns with your Adyen module configuration, I would advise checking the following:

- Open your Magento admin
- Select `System -> Configuration` from the header dropdown menu
- Click on `Payment Methods` in the sidebar
- Scroll down to the `Adyen Default Settings` section
- Check the following configuration values within the `Required Settings` subsection
- `Order status: order creation`, `Order status: payment authorisation`, `Order status: payment confirmed`

On a slight tangent, I thinks it's also worth mentioning that it's probably not a good idea to publicly leak PSP references for payments on your stores, as I understand it this information isn't generally exposed.

**Comment by seansan** [comment] 2017-04-15 12:27
I am checking the settings

1) Order status: payment authorisation = `Status given to orders after
authorisation confirmed by an AUTHORISATION notification from Adyen. Note:
an authorisation status via the result URL does not yet trigger this status.
`

2) Order status: payment confirmed = `Status given to orders after capture
result is confirmed by an AUTHORISATION notification (if capture mode =
immediate) or a CAPTURE notification (if capture mode = manual capture)
from Adyen.`

TBH I dont fully understand the descriptions. Capture mode is immediate.

In the first it reads "Status given to orders after authorisation confirmed
by an AUTHORISATION notification" meaning the AUTHORISATION notification
confirms the authorisation

In the second it reads "Status given to orders after capture result is
confirmed by an AUTHORISATION notification" meaning the AUTHORISATION
notification confirms the capture result

Questions:
1. if Order status: payment confirmed is set and Capture mode is immediate
am I then to understand that Order status: payment authorisation is not
used? (not applicable). An order is eother then new (not auth) or it is
confirmed (auth)
2. What is the difference between the two - the tooltip seems to explain
that the AUTHORISATION notification does two things. In case 1 confirm the
authorization. and in case 2 it confirms the capture result. Which one of
the 2 does it confirm?

3. And maybe last: witht he aims to solve this. If we capture immediate.
Sell stuff online. What are the 2 suggested settings for these config
values?

Hoping you can shed some light ;)

**Comment by seansan** [comment] 2017-04-15 12:31
And sorry to reply again. But more highlevel: if an order is confirmed
(authorized and all): why should it every be allowed to go back in status?
(i mean how can it becoma unpaid again if it is already paid)

**Comment by rikterbeek** [comment] 2017-04-18 11:14
Hi @seansan,

The status is set to pending because your "Order status: payment authorisation" status is set to "Wacht op authorisatie" this should go to processing state if you have the status "Order status: payment confirmed" set to a status. Looks like you are missing one comment history item that is providing you this status. Do you have exception in your notification processing ? see image below how it should looks like for an ideal payment (ofcourse status could be different)

![download](https://cloud.githubusercontent.com/assets/5948499/25128147/e55d1b20-2438-11e7-93c4-d187184f3ee1.png)

Regards,
Rik
Adyen

**Comment by seansan** [comment] 2017-04-18 12:39
We have several like this

Seems to occur when a payment link is sent .... can it be that it only occurs there?

I search for the psp ref in logs but 0 hits

![image](https://cloud.githubusercontent.com/assets/652395/25130964/646bc334-2444-11e7-94b7-d8db54e79b28.png)

![image](https://cloud.githubusercontent.com/assets/652395/25130981/747e78fc-2444-11e7-891d-5aa18368bf5f.png)

**Comment by rikterbeek** [comment] 2017-04-25 09:20
Hi Sean,

What I do not understand of your screenshot is the Adyen Result Url comment history because the skin should not return to your shop at all for Payment Links. And you are missing the latest statement. Can you check your logs what has happened with the notification processing.
![screen shot 2017-04-25 at 11 19 24 am](https://cloud.githubusercontent.com/assets/5948499/25377921/27436682-29a9-11e7-9c65-bc1a316b8478.png)

Regards,
Rik
Adyen

**Comment by seansan** [comment] 2017-04-26 07:38
Hi Rik, thanks

See below this is full log
![image](https://cloud.githubusercontent.com/assets/652395/25423201/13d91270-2a64-11e7-94d1-8e6b242b48f0.png)

In adyen I see this
![image](https://cloud.githubusercontent.com/assets/652395/25423211/1c7a6618-2a64-11e7-9faf-a42a896ff415.png)

And sorry this PSP is found nowhere in logging cat * | grep ...

I will PM you the PSP ref

**Comment by rikterbeek** [comment] 2017-04-26 16:00
Hi @seansan,

We need the actual logs please raise your question to magento@adyen.com together with the adyen_process_notification_cron.log where we can help you out. Closing this issue here.

Regards,
Rik
Adyen

**Closed by rikterbeek** 2017-04-26 16:00 UTC
